data:
  path: '/data/malek/dog_cat_classification/test'
  batch_size : 12

model_to_load : 'resnet50'   #

checkpoint :
  path: '/data/malek/dog_cat_classification/checkpoints/best.ckpt' #make sure to put the right path to ckpt file
